// <auto-generated />
namespace Register.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class telephAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(telephAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201911210921458_telephAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
